package mod.upcraftlp.cds.proxy;

import mod.upcraftlp.cds.blocks.tile.TileEntityPortalBase;
import mod.upcraftlp.cds.client.render.tile.TileEntityPortalBaseRenderer;
import mod.upcraftlp.cds.client.render.WorldRenderHandler;
import mod.upcraftlp.cds.entity.EntityPortal;
import mod.upcraftlp.cds.client.render.entity.RenderPortalEntity;
import net.minecraft.client.Minecraft;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ClientProxy extends CommonProxy {

	@Override
	public void preInit(FMLPreInitializationEvent event) {
		super.preInit(event);
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPortalBase.class, new TileEntityPortalBaseRenderer());
		RenderingRegistry.registerEntityRenderingHandler(EntityPortal.class, RenderPortalEntity.FACTORY);

		/**mcmod.info**/
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		//TODO: metadata!
	}
	
    @Override
	public void init(FMLInitializationEvent event) {
		super.init(event);
	}
	
	@Override
	public void postInit(FMLPostInitializationEvent event) {
		super.postInit(event);
		Minecraft mc = Minecraft.getMinecraft();
		mc.resize(mc.displayWidth, mc.displayHeight);
	}

	@Override
	public void killPortal(EntityPortal portal) {
		super.killPortal(portal);
		WorldRenderHandler.pendingRemoval.add(portal);
	}
}
